#!/usr/bin/env python3

# res_copy.py
# This script copies files from the RES_DIR and bakes them into 
# a C header file (files.h) in the OUTFILE_DIR.


import os

RES_DIR = os.path.abspath("../res");
OUTFILE_DIR = os.path.abspath("./src/files.h")
EXCLUDE_EXT = [".pyxel"]
NUM_FILES = sum(
  1
  for root, _, files in os.walk(RES_DIR)
  for file in files
  if not any(file.endswith(ext) for ext in EXCLUDE_EXT)
)

# Add newlines at the end of each line in the file content
# This is necessary for the C code to properly interpret the file content
# as a string literal with line breaks.
def fmt_file(text):
  lines = text.splitlines()
  lines = [line + '\\n' for line in lines]

  return f'"{lines}"'


# Adds a file from RES_DIR to the output file in the format:
# {
#   name = "path/to/file.txt",
#   data = "file content with \\n at the end of each line"
#   size = 1234
# }
def generate_file_obj(outfile, file_path, content, length):
  outfile.write(f'\t{{\n\t\t"{os.path.relpath(file_path, RES_DIR)}",\n')
  outfile.write(f'\t\t{content},\n')
  outfile.write(f'\t\t{length}\n')
  outfile.write('\t},\n')


# Populates each generated FileEntry struct with the raw bytes from the source file
def add_file(file_path, outfile):
  if any(file_path.endswith(ext) for ext in EXCLUDE_EXT):
    return

  print (file_path)
  with open(file_path, "rb") as f:
    raw_content = f.read()
    num_bytes = len(raw_content)
    bytes_str = ', '.join([f'0x{b:02X}' for b in raw_content])

    content = '(const unsigned char[]){ ' + bytes_str + ' }' #bake in a null terminator
    generate_file_obj(outfile, file_path, content, num_bytes)
    

print("Resource Directory:", RES_DIR)
print("Output File:", OUTFILE_DIR)

# Create the output file and write the header
output = open(OUTFILE_DIR, "w")
output.write("// This file is auto-generated by res_copy.py\n")
output.write("// Do not edit manually.\n\n")
output.write('struct FileEntry {\n'
              '\t\tconst char* name;\n'
              '\t\tconst unsigned char *data;\n'
              '\t\tunsigned int size;\n'
              '};\n\n'
              'const FileEntry files[] = {\n'
             )

# Walk through the RES_DIR and add each file to the output
for root, dirs, files in os.walk(RES_DIR):
  for file in files:
    file_path = os.path.join(root, file)
    add_file(file_path, output)


# Close the file entry array and write the number of files
output.write('};\n\n')
output.write(f'const int num_files = {NUM_FILES};\n')
output.write('\n\n// End of auto-generated file\n')

output.close()
print(f"Resource files copied to {OUTFILE_DIR}")