name: macOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        threading: [ON, OFF]

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DSHADER_WORKS_USE_THREADS=${{ matrix.threading }} \
              ..

    - name: Build
      run: |
        cd build
        cmake --build . -j $(sysctl -n hw.ncpu)

    - name: Verify binaries exist
      run: |
        ls -lh build/bin/
        file build/bin/tundra
        file build/bin/microcraft

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.build_type }}-threads-${{ matrix.threading }}
        path: |
          build/bin/
          build/lib/
        retention-days: 5