name: Windows Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        threading: [ON, OFF]

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-python-pillow
          git

    - name: Configure and Build
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DSHADER_WORKS_USE_THREADS=${{ matrix.threading }} \
              ..
        cmake --build . -j $(nproc)

    - name: Verify binaries exist
      shell: msys2 {0}
      run: |
        ls -lh build/bin/
        file build/bin/tundra.exe
        file build/bin/microcraft.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.build_type }}-threads-${{ matrix.threading }}
        path: |
          build/bin/*.exe
          build/lib/*.a
        retention-days: 5