name: Windows Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        threading: [ON, OFF]

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          git

    - name: Configure and Build
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DSHADER_WORKS_USE_THREADS=${{ matrix.threading }} \
              ..
        cmake --build . -j $(nproc)

    - name: Test demo runs
      shell: msys2 {0}
      run: |
        cd build/bin
        ./01_spinning_cube.exe &
        DEMO_PID=$!
        sleep 10
        kill $DEMO_PID 2>/dev/null || true
        wait $DEMO_PID 2>/dev/null || echo "Windows 01_spinning_cube test completed"

        ./03_fps_controller.exe &
        FPS_PID=$!
        sleep 10
        kill $FPS_PID 2>/dev/null || true
        wait $FPS_PID 2>/dev/null || echo "Windows 03_fps_controller test completed"

        ./02_textured_scene.exe &
        FULL_PID=$!
        sleep 10
        kill $FULL_PID 2>/dev/null || true
        wait $FULL_PID 2>/dev/null || echo "Windows 02_textured_scene completed"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.build_type }}-threads-${{ matrix.threading }}
        path: |
          build/bin/*.exe
          build/lib/*.a
        retention-days: 5